# Generated by Django 3.1.4 on 2020-12-30 00:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(18)], verbose_name='Возраст')),
                ('position', models.CharField(max_length=60, verbose_name='Должность')),
                ('photo', models.ImageField(upload_to='employees/', verbose_name='Фото')),
                ('achievements', models.TextField(help_text='Информация об образовании, опыте, квалификации и профессиональных достижениях', max_length=2000, verbose_name='Достижения')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Фото')),
                ('warranty', models.PositiveSmallIntegerField(choices=[(0, ''), (1, '6'), (2, '12'), (3, '24')], help_text='Указать в месяцах', verbose_name='Гарантийный срок')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Указывать сумму в рублях', max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость услуги')),
                ('url', models.SlugField(max_length=130, unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category', verbose_name='Категория')),
                ('employee', models.ManyToManyField(related_name='service_employee', to='api.Employee', verbose_name='Cотрудник')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
